# Generated by Django 2.0.3 on 2018-03-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('logo', models.ImageField(upload_to='')),
                ('delivery_available', models.BooleanField()),
                ('delivery_details', models.CharField(default="This restaurant doesn't deliver", max_length=250)),
                ('signature_dish', models.CharField(max_length=250)),
                ('address', models.URLField(max_length=500)),
                ('website', models.URLField()),
                ('fb_page', models.URLField()),
            ],
        ),
    ]
