# Generated by Django 2.0.3 on 2018-03-11 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0002_auto_20180311_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='city',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='country',
            field=models.CharField(default=0, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='postcode',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurants',
            name='slug',
            field=models.SlugField(default=0, max_length=250),
            preserve_default=False,
        ),
    ]
