# Generated by Django 2.0.3 on 2018-03-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Restaurants', '0003_auto_20180311_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurants',
            name='category',
        ),
        migrations.AddField(
            model_name='restaurants',
            name='category',
            field=models.ManyToManyField(to='Restaurants.RestaurantCategory'),
        ),
    ]
