# Generated by Django 2.0.3 on 2018-03-11 09:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_main', '0005_auto_20180311_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 11, 9, 39, 54, 845540, tzinfo=utc)),
        ),
    ]
