# Generated by Django 2.0.3 on 2018-03-11 09:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog_main', '0006_auto_20180311_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 11, 9, 49, 41, 910480, tzinfo=utc)),
        ),
    ]
